# # it's a "play"
- hosts: docker
  vars_files:
    - "vars/vars.yml"
  pre_tasks:
    - file:
        path: "/home/{{ remote_user }}/.infra/stacks/{{ docker_stack_name }}"
        state: absent
    - file:
        path: "/home/{{ remote_user }}/.infra/stacks/{{ docker_stack_name }}"
        state: directory
  roles:
    - "{{ docker_stack_name }}"
  post_tasks:
    - name: Find j2 files
      find:
        paths: "roles/{{ docker_stack_name }}/templates"
        patterns: "^.*?\\.j2$"
        use_regex: true
        recurse: true
      register: found_templates
      delegate_to: localhost

    - name: Ensure destination directories exist
      file:
        path: >-
          /home/{{ remote_user }}/.infra/stacks/{{ docker_stack_name }}/{{
            item.path
            | regex_replace('^roles/traefik/templates/', '')
            | dirname
          }}
        state: directory
        mode: "0755"
      loop: "{{ found_templates.files }}"

    - name: Templating found files
      template:
        src: "{{ item.path }}"
        dest: >-
          /home/{{ remote_user }}/.infra/stacks/{{ docker_stack_name }}/{{ item.path | regex_replace('^roles/traefik/templates/', '')| regex_replace('\.j2$', '') }}
      loop: "{{ found_templates.files }}"
# - hosts: docker_swarm_primary_manager
#   vars_files:
#     - "vars/vars.yml"
#   tasks:
#     - name: "Deploy stack {{ docker_stack_name }}"
#       docker_stack:
#         state: present
#         name: "{{ docker_stack_name }}"
#         with_registry_auth: "yes"
#         compose:
#           - "/home/{{ remote_user }}/.infra/stacks/{{ docker_stack_name }}/{{ docker_stack_name }}.yml"
