#SPDX-License-Identifier: MIT-0
---
# tasks file for playbooks/scripts/roles/default
- name: Check python version
  debug:
    var: ansible_python_version

- name: Show inventory hostname
  debug:
    var: ansible_hostname
